### ISSUE TITLE
possible missing dependencies

### ISSUE THREAD

**Issue by tet-web-dev** [reidspreiter/pdf-coordinate-finder#1]
the referenced files in the import aren't present. 
cv2,fitz, os 
![image](https://github.com/reidspreiter/pdf-coordinate-finder/assets/6007105/b57b3cc4-e250-44f5-b1c9-a2a31153faa0)

I have a c# javascript background so forgive me in advance if I'm missing something. Thanks!

**Comment by Dumbo-programmer** [comment]
they're python dependencies.

**Comment by reidspreiter** [comment]
Apologies for getting back to this so late @tet-web-dev. This is essentially the first thing I ever programmed, and I was unfamiliar with good release habits at the time. My past self would be honored to know that someone else wanted to use this.

I pushed changes which added installation instructions to the README and made the script more user friendly.

Thanks for opening this issue!
